### PR TITLE
Added : More Social Media

### PR DESCRIPTION
**Pull request by ARBoyGo**

### CODE REVIEW

**Comment by faisalcodes** [comment]
The links are taking a lot of space. Can you minimize it?

**Comment by ARBoyGo** [comment]
Keep this PR here, I'll design widget. Probably you need to add it to your website even if I designed it. 

Why not make your site open source, So anyone can help, you just need to push it from your host server.

**Comment by faisalcodes** [comment]
> Keep this PR here, I'll design widget. Probably you need to add it to your website even if I designed it.

Okay! mark this as draft then.

> Why not make your site open source, So anyone can help, you just need to push it from your host server.

Good idea! I'll do that, InshaAllah

**Comment by faisalcodes** [comment]
I need to work on the features before I can work on the website. FYI, the website is built with ReactJs and hosted on Firebase.

**Comment by ARBoyGo** [comment]
Please merge and pull https://github.com/AlfaazPlus/QuranApp-site/pull/1

**Comment by ARBoyGo** [comment]
Added to repo-assets

**Review by faisalcodes — APPROVED** [review]

**Pull request merged**
