### PR TITLE
Update onboard.xml

### PR DESCRIPTION
**Pull request by Mylinde**
In German we have two meanings for "you". First is "Sie" with this we address strangers, second is "du" with this we address acquaintances and friends. Wich kind will you preffer in your app? I have chosen "Sie" in all translations, because it is common in everyday life.

### CODE REVIEW

**Comment by faisalcodes** [comment]
The purpose is that people should easily understand the meaning. Also it should appear friendly to them. In this case what do you think should be used?

**Comment by Mylinde** [comment]
Asked the children what they will expect and they meant, to stay at "Sie" for the first. It is more polite.

**Comment by faisalcodes** [comment]
> Asked the children what they will expect and they meant, to stay at "Sie" for the first. It is more polite.

Then, you should keep using it.

**Comment by faisalcodes** [comment]
You PR is conflicting after I changed some structure of the codes. Let me fix it.

**Review by faisalcodes — APPROVED** [review]

**Comment by faisalcodes** [comment]
@Mylinde May you join our [discord server](https://discord.com/invite/vtutnwzxRb)?

**Pull request merged**
