### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [QuranApp/QuranApp](https://hosted.weblate.org/projects/QuranApp/QuranApp/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by faisalcodes — APPROVED** [review]

**Comment by faisalcodes** [comment]
@rchookan Brother! Could you please add remaining translations? And thank you for your contributions.

**Comment by rchookan** [comment]
> @rchookan Brother! Could you please add remaining translations? And thank you for your contributions.

Hello, I will translate the rest of the texts into Farsi soon

**Comment by rchookan** [comment]
> @rchookan Brother! Could you please add remaining translations? And thank you for your contributions.

I have a religious application, but it has a bug. Can you help me fix the application bug?

**Comment by faisalcodes** [comment]
> I have a religious application, but it has a bug. Can you help me fix the application bug?

Give me link to the app, I will check it out.

**Comment by rchookan** [comment]
> > I have a religious application, but it has a bug. Can you help me fix the application bug?
> 
> Give me link to the app, I will check it out. Kindly do not share the link here. You could contact me on [Instagram](https://www.instagram.com/faisalcodes/)

Ok.
 
I completed the Persian Translation.

**Pull request merged**
