### PR TITLE
initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
For your [RFP with F-Droid](https://gitlab.com/fdroid/rfp/-/issues/2387). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to build upon this (e.g. adding per-release changelogs, starting with the most recent one). As usual, should you have questions, just ask :smiley:

### CODE REVIEW

**Comment by faisalcodes** [comment]
The full description seems to be older. May it be updated with the latest one?

**Comment by IzzySoft** [comment]
You can update it anytime after the merge (that's the idea of you having it here in Fastlane format) – just make sure you don't break it :see_no_evil:

I've used "compressed HTML" here as this works best for F-Droid's and my repo – not sure if it would work with Play. Do you intend to use fastlane for PlayStore as well? And do you really need those Unicode icons as bullet points? Just asking so I know how I should format it. Options we'd have:

* using "plain text" as you'd do for PlayStore. Con: Doesn't look that nice – especially for bullet-point items exceeding screen width (like the last one above).
* using "Markdown Lite" (basically "plain text" again, but in a way it would render as "proper Markdown". Pro: nicer formatting with my repo. Con: same as "plain text" with PlayStore & F-Droid
* using "direct HTML" (as it is now). Pro: formats well with F-Droid and my Repo. Cons: a little harder to edit, and not sure how it behaves with PlayStore.

Those "Unicode icons" might be easy to use with "plain text", but would cause difficulties with the other two. So what's your choice – so I might update it once more before you merge?

**Comment by faisalcodes** [comment]
I just copied the description which I wrote on the Play Store with no changes. Play store allows no/minimal formatting so I thought inserting emojis would make the sections distinct. But there doesn't seem universal formatting support on all these platforms, so you may make changes the way you think is better. I might learn a new thing from this.

Yes, I have planned to set up fastlane for the play store as well. If formatting is not possible universally then inserting a new line between sections should also do the job.

**Comment by IzzySoft** [comment]
> If formatting is not possible universally then inserting a line breaks between sections should also do the job.

Yes, that would work fine with Markdown as well. So shall I go with "Markdown Lite" here – or just provide it using the same HTML formatting it has now? If you prefer deploying it to PlayStore as well you'll probably need to re-format anyway, so maybe I start that with that right away then? Do you know what formatting options Google permits, maybe even have a link to that? I'm pretty sure they allow at least for `<b>`old and things like that. If you can let me know, I can incorporate that as well (would also help other projects if I can give clear advice next time).

> My query in the last comment was actually about the content of the description.

Yes, sure, and I was aware of that. But if you want *me* to apply the changes, I should do them in a more useful way :wink:

**Comment by faisalcodes** [comment]
> Yes, sure, and I was aware of that. But if you want me to apply the changes, I should do them in a more useful way

It would be highly appreciated if you do it.

Yes google play supports `<b>`. I found the following image on the internet. All the things mentioned here don't have good support though. As I have tested it myself the google play **website** and **app** both parses the html content differently. So it is better to only use common tags such as `<b>`, `<i>` etc.



If you check out the QuranApp's description in the [main store listing](play.google.com/store/apps/details?id=com.quranapp.android) on both — app and website, I have done it using the following text:

<details>
<summary>Full description from the play store</summary>


```

The QuranApp is an ad-free and privacy-focused mobile application that facilitates reading and exploring the Holy Qur’an on daily basis at any time and place. Its easy-to-navigate and neat and clean design helps users to overcome the difficulties of reading the Qur’an in the time of technology. This app has 15+ translations in several languages so that people of different languages and regions can understand the purpose of the Qur’an.


~~~~~~~

<h2>Salient Features of the QuranApp</h2>
The following features are the reason why you should use the QuranApp.

<b>🛡️ Pure</b>
- Open source
- No ads or purchases
- No phone permission is required
- No analytics or tracking
- No data collection or sharing

<b>📙 Translations</b>
- 15+ Translations
- Read multiple translations together
- Quick preview of footnotes
- Quick preview of verse references

<b>🎙️ Recitations</b>
- 15+ Recitations
- Repeat single verse
- Play verse range
- Play recitation continuously
- Automatic scroll to match current verse

<b>🎨 Fonts</b>
- Multiple fonts (Uthmani, Indopak and KFQPC)
- Customize Arabic text size
- Customise translation text size

<b>⚙ Layout</b>
- Reading in translation mode
- Reading in page mode
- Read Qur'an in different translation modes (single verse, verse range, full chapter, full juz)

<b>➡️ Navigation</b>
- Convenient navigation in single verse mode
- Quickly jump to any verse
- Quickly jump to any chapter
- Quickly jump to any juz

<b>❤️ Contents from the Qur'an</b>
- Topics from the Qur'an
- Duas from the Qur'an
- Prophets mentioned in the Qur'an

<b>🔍 Search</b>
- Advanced search
- Voice search
- Search history
- Easily navigate to any translation in search results
- Search for full word or word part

<b>📌 Bookmarking</b>
- Bookmark verses for later
- Bookmark single verse
- Bookmark a verse range
- Add custom notes to bookmarks

<b>🔥 Other Features</b>
- Verse of the Day Reminder
- Advanced sharing
- Dark and light themes
- Multiple language support

<i>🐞 To report an issue or request a new feature, kindly visit the GitHub repository at https://github.com/AlfaazPlus/QuranApp <i>

```

</details>

**Comment by IzzySoft** [comment]
Your pic is incomplete (taken [from here](https://stackoverflow.com/a/65464120/2533433)?) – guess I just found the original:

image

([source](https://phiture.com/asostack/enhance-your-google-play-store-description-with-rich-formatting-and-emojis-5f50ff354e5f/)) Quite confusing rules they have, as usual… If I got that right, unsupported tags will simply be stripped. `<h2>` would be replaced in my repo by "bold + big", to not interfere with the page structure (I wonder Google permits that); I've just updated [my formatting hints](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) accordingly.

So if you agree, we could take your proposed formatting with some minor adjustments:

* insert a blank line in front of each bullet-point list  (to make it Markdown compliant)
* fix the closing tag in the last line (it's currently an opening tag :see_no_evil:)
* replace the link in the last line by `<a href='https://github.com/AlfaazPlus/QuranApp'>Github</a>` to make it render as link everywhere
* `<h2>` might break structures and look ugly at least in F-Droid's web site. As Google also supports `<h3>`, maybe downgrade it to that?

That would be a good compromise for all 3 places then (we cannot make it perfect for each, unfortunately).

**Comment by faisalcodes** [comment]
I agree with you we should apply the changes as you have proposed. Kindly do that on your part. 

> fix the closing tag in the last line (it's currently an opening tag 🙈)

 I didn't notice, copy-paste leaves some mistakes behind. I was writing directly in the browser.

**Comment by IzzySoft** [comment]
OK, there you go. Once your app is listed at F-Droid it's usually removed from my repo (unless its author explicitly requested it to stay). At that point you might wish to "drop" the extra empty lines at the top of each bullet-point list (which is only needed to make it proper Markdown for more beautiful rendedering with my repo).

**Review by faisalcodes — APPROVED** [review]

**Comment by faisalcodes** [comment]
I will be prepared when needed.

**Pull request merged**
