### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [QuranApp/QuranApp](https://hosted.weblate.org/projects/QuranApp/QuranApp/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by faisalcodes — APPROVED** [review]

**Comment by faisalcodes** [comment]
@rashidi77 Thank you for your contribution.

**Comment by rashidi77** [comment]
jazakumullah. I hope you never put Google ads in the app UI.

**Comment by faisalcodes** [comment]
It is open source forever. 😊 Insha Allah

**Comment by faisalcodes** [comment]
@rashidi77 
Brother can you please further translate the app? It has new strings (around 40) added.

**Pull request merged**
