### PR TITLE
Update quran_meta.json

### PR DESCRIPTION
**Pull request by Mylinde**
Salem aleikum,

added german translation.

### CODE REVIEW

**Comment by faisalcodes** [comment]
Walaikum assalam, Thank you again for your contribution. I will verify and merge it shortly.

**Comment by faisalcodes** [comment]
@Mylinde Could you tell me what source did you use to translate this file?

**Review by faisalcodes — APPROVED** [review]

**Comment by faisalcodes** [comment]
Haha @Mylinde you got the order of prophets wrong. The site you referenced has a random order and you thought it is same as in the file.

**Comment by Mylinde** [comment]
@faisalcodes 

Haha, I haven't changed the order in your source.
😎

**Comment by Mylinde** [comment]
Abi, can you please check the order in your file? Because is different from other sources e.g.
IMG_20230817_200659
IMG_20230817_200724

**Comment by faisalcodes** [comment]
Looks like I need to verify it again..

**Pull request merged**
